name: FP-Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Replace default tox.ini with custom version
        run: |
          cp fp_tox.ini tox.ini

      - name: Insert netaddr into execution-environment.yml
        run: |
          sed -i '/python: |/a \ \ netaddr' execution-environment.yml

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker -- --tag=ghcr.io/fpm-git/awx-ee:${{ github.event.release.tag_name }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply latest tag
        run: |
         docker tag ghcr.io/fpm-git/awx-ee:${{ github.event.release.tag_name }} ghcr.io/fpm-git/awx-ee:latest

      - name: Push images
        run: |
         docker push ghcr.io/fpm-git/awx-ee:${{ github.event.release.tag_name }}
         docker push ghcr.io/fpm-git/awx-ee:latest
