name: Sync to Upstream

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: devel

    - name: Set Git Pull Strategy
      run: git config pull.rebase false


    - name: Pull upstream changes
      id: sync
      uses: bdougie/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: ansible/awx-ee
        upstream_sync_branch: devel
        target_sync_branch: devel
